### ISSUE TITLE
Code missing

### ISSUE THREAD

**Issue by funtax** [mbolek/locust_exporter#1]
Hey there,

we would love to use your code in our environments.
But sadly the code (eg. locust_exporter.py) is missing.

Could you please add it to the repository?
Otherwise it seems that this repo is not usable right now.

Thanks in advance & kind regards,
Martin

**Comment by mbolek** [comment]
Hi @funtax, I've added the code - I guess I forgot about it and haven't used it recently in general but I just did a quick smoke test and it seems to work :) If you have any issues let me know and I'll try to help.
Cheers

**Comment by funtax** [comment]
Great, thank you :)
