### ISSUE TITLE
what is the next step after ./locust_exporter.py 1234 localhost:8089

### ISSUE THREAD

**Issue by jiuchongxiao** [mbolek/locust_exporter#3]
what is the next step after ./locust_exporter.py 1234 localhost:8089?

my result ./locust_exporter.py 1234 localhost:8089 as below:
![image](https://user-images.githubusercontent.com/13093730/42160509-18ea26da-7e2a-11e8-9d26-a940cdc1f72e.png)

what is the next step,and how to show the example result?

![image](https://user-images.githubusercontent.com/13093730/42160554-412ca2ee-7e2a-11e8-9977-7856fd5b487e.png)

**Comment by jiuchongxiao** [comment]
@kirknorthrop @mbolek

**Comment by mbolek** [comment]
@jiuchongxiao try opening your browser and pointing it to: `http://localhost:8089`

**Comment by jiuchongxiao** [comment]
yeah,i get the below,it is the locust  page. but how to view the collector datas? @mbolek 
![image](https://user-images.githubusercontent.com/13093730/42161713-96b66e08-7e2e-11e8-8886-508b7f25899a.png)

**Comment by mbolek** [comment]
Are you sure it is 8089 on localhost? @jiuchongxiao 
You are running locust_exporter on port 8089 locally and locust server on 192.168.181.9:30089

**Comment by jiuchongxiao** [comment]
oh,sorry my error. i use locust by kubernetes cluster ,and i use the 8089 repeat with the kubernetes service,so i view by NodePort .


it is worked now ,thank you very much.

i will use the result to promethues's exporter and show the result with grafana. if you have the next step to integrate the promethues-operator ,it will perfect. haha    thank you again.

**Comment by jiuchongxiao** [comment]
![image](https://user-images.githubusercontent.com/13093730/42162350-f05e0fc2-7e30-11e8-8512-70292841269a.png)
haha   ,i foget show my kubernetes service config.

**Comment by mbolek** [comment]
mystery solved then:)
sorry, I don't use prometheus-operator
